export const questions = [
  {
    id: 1,
    question: "India has been a land of great cultures since ancient times including.......",
    options: {
      A: "Hinduism",
      B: "Jainism",
      C: "Buddhism",
      D: "All of these",
    },
    answer: "D",
  },
  {
    id: 2,
    question:
      "Bharatiya Knowledge System has been evident from the era of Harappan Civilization which was started from...............................",
    options: {
      A: "2600-1900 BCE",
      B: "3600-900 BCE",
      C: "6600-2900 BCE",
      D: "5600-3900 BCE",
    },
    answer: "A",
  },
  {
    id: 3,
    question: "Mohenjodaro in Sind province is now located in...............",
    options: {
      A: "Bhutan",
      B: "Sri Lanka",
      C: "India",
      D: "Pakistan",
    },
    answer: "D",
  },
  {
    id: 4,
    question: "What is Pyrotechnology?",
    options: {
      A: "Crafts created using fire",
      B: "Crafts created without use of fire",
      C: "Crafts created using water and soil",
      D: "None of these",
    },
    answer: "A",
  },
  {
    id: 5,
    question: "What is the time period of colonial period in India?",
    options: {
      A: "From 1500 CE - 1747 CE",
      B: "From 1700 CE - 1947 CE",
      C: "From 1600 CE - 1847 CE",
      D: "None of these",
    },
    answer: "B",
  },
  {
    id: 6,
    question: "India has been a land of great cultures since ancient times including.......",
    options: {
      A: "Hinduism",
      B: "Jainism",
      C: "Buddhism",
      D: "All of these",
    },
    answer: "D",
  },
  {
    id: 7,
    question:
      "............................. is the ultimate goal of human life, representing liberation from the cycle of birth and death.",
    options: {
      A: "Karma",
      B: "Maya",
      C: "Atman",
      D: "Moksha",
    },
    answer: "D",
  },
  {
    id: 8,
    question: "Shakuntala is dramatic literature written by.........................",
    options: {
      A: "Surdasa",
      B: "Kalidasa",
      C: "Tulsidasa",
      D: "Narottamdasa",
    },
    answer: "B",
  },
  {
    id: 9,
    question:
      "Ajanta and Ellora caves contain some of the finest examples of classical Indian painting, depicting scenes from the life of...................................",
    options: {
      A: "Hinduism",
      B: "Buddhism",
      C: "Both Hinduism and Buddhism",
      D: "Sikkhism",
    },
    answer: "C",
  },
  {
    id: 10,
    question: "What is the time period of vedic period in India?",
    options: {
      A: "From 1000 BCE - 500 BCE",
      B: "From 1500 BCE - 500 BCE",
      C: "From 2000 BCE - 1500 BCE",
      D: "All of these",
    },
    answer: "B",
  },
  {
    id: 11,
    question: "The illusionary nature of the world is also known as...........",
    options: {
      A: "Karma",
      B: "Maya",
      C: "Atman",
      D: "Moksha",
    },
    answer: "B",
  },
  {
    id: 12,
    question: "The entire body of knowledge is divided into ....... sets in Mundakupanishad.",
    options: {
      A: "0",
      B: "1",
      C: "2",
      D: "3",
    },
    answer: "C",
  },
  {
    id: 13,
    question: "Aṣṭādhyāyī is a grammer book written by...........",
    options: {
      A: "Aryabhatta",
      B: "Brahmgupta",
      C: "Panini",
      D: "None of these",
    },
    answer: "C",
  },
  {
    id: 14,
    question: "Sage Gautam is famous for his contribution about the scripture related to...................",
    options: {
      A: "Vaisheshika",
      B: "Samkhya",
      C: "Nyaya",
      D: "None of these",
    },
    answer: "C",
  },
  {
    id: 15,
    question: "Who is known as the father of Vedanta?",
    options: {
      A: "Gautam",
      B: "Kanad",
      C: "Jamini",
      D: "Veda Vyas",
    },
    answer: "D",
  },
  {
    id: 16,
    question: "Philosophical study of being, existence, and reality is known as........................",
    options: {
      A: "Phenology",
      B: "Oncology",
      C: "Ontology",
      D: "None of these",
    },
    answer: "C",
  },
  {
    id: 17,
    question:
      "In traditional knowledge of India, water and fire are known as.........................and ......................., respectively.",
    options: {
      A: "Ap and Tejas",
      B: "Vayu and Tejas",
      C: "Tejas and Akasha",
      D: "All of these",
    },
    answer: "A",
  },
  {
    id: 18,
    question: "Mimamsa means..........",
    options: {
      A: "Science education",
      B: "Art education",
      C: "Critical investigation",
      D: "Economics education",
    },
    answer: "C",
  },
  {
    id: 19,
    question: "Sage Patanjali has given the concept of............................",
    options: {
      A: "Nyaya",
      B: "Yoga",
      C: "Vaisheshika",
      D: "None of these",
    },
    answer: "B",
  },
  {
    id: 20,
    question: "Apara Vidhya means.........",
    options: {
      A: "Sanskrit",
      B: "The higher knowledge",
      C: "The lower knowledge",
      D: "All of these",
    },
    answer: "C",
  },
  {
    id: 21,
    question: "Which one is famous for foundational principles governing health, disease, diagnosis, and treatment.",
    options: {
      A: "Vaisheshika",
      B: "Āyurveda",
      C: "Apara vidhya",
      D: "Para vidhaya",
    },
    answer: "B",
  },
  {
    id: 22,
    question: "What was the time period of Gupta script?",
    options: {
      A: "From 4th to 6th century CE",
      B: "From 6th to 8th century CE",
      C: "From 8th to 10th century CE",
      D: "From 10th to 12th century CE",
    },
    answer: "A",
  },
  {
    id: 23,
    question: "Isa is a type of ...........",
    options: {
      A: "Upanishads",
      B: "Puranas",
      C: "Grammer",
      D: "None of these",
    },
    answer: "A",
  },
  {
    id: 24,
    question: "How many Parvas are in Mahabharata?",
    options: {
      A: "18",
      B: "28",
      C: "38",
      D: "48",
    },
    answer: "A",
  },
  {
    id: 25,
    question: "Which ancient and sacred scriptures are known as the foundation of Hinduism?",
    options: {
      A: "Vedas",
      B: "Bhagvad Gita",
      C: "Ramayana",
      D: "Mahabhartha",
    },
    answer: "A",
  },
  {
    id: 26,
    question: "In Hinduism, Yajna (Sacrifice) means",
    options: {
      A: "Emphasis on purity and precision in the execution of rituals",
      B: "Performing rituals and sacrifices to appease the gods and maintain cosmic order",
      C: "Contains prose mantras used in rituals",
      D: "Detailed explanations of the rituals and their significance",
    },
    answer: "B",
  },
  {
    id: 27,
    question: "What are Agamas and Tantras?",
    options: {
      A: "Collection of ethical guidelines",
      B: "Role of different dities",
      C: "Base of various religious and spiritual practices",
      D: "None of these",
    },
    answer: "C",
  },
  {
    id: 28,
    question: "Music is originated from............",
    options: {
      A: "Rk veda",
      B: "Yajur Veda",
      C: "Sama veda",
      D: "Atharva Veda",
    },
    answer: "C",
  },
  {
    id: 29,
    question:
      "The Vedas are the oldest and most authoritative scriptures of Hinduism. They consist of ....... main collections.",
    options: {
      A: "2",
      B: "3",
      C: "4",
      D: "5",
    },
    answer: "C",
  },
  {
    id: 30,
    question: "Devanagari Script was developed in.........centuary.",
    options: {
      A: "9th century CE",
      B: "8th century CE",
      C: "7th century CE",
      D: "6th century CE",
    },
    answer: "A",
  },
  {
    id: 31,
    question:
      "A concise and aphoristic style of writing used in ancient Indian literature, particularly within the realms of philosophy, spirituality, law, and grammar?",
    options: {
      A: "Karma",
      B: "Darshana",
      C: "Tantras",
      D: "Sutras",
    },
    answer: "D",
  },
  {
    id: 32,
    question: "In which ancient scripture, social customs, ethics of human behaviour have been mentioned?",
    options: {
      A: "Smritis",
      B: "Sutras",
      C: "Puranas",
      D: "Gita",
    },
    answer: "A",
  },
  {
    id: 33,
    question: "Tripitaka scripture is related to.............",
    options: {
      A: "Hinduism",
      B: "Jainism",
      C: "Buddhism",
      D: "Sikkhism",
    },
    answer: "C",
  },
  {
    id: 34,
    question: "Which one comprises translations of the Buddha's teachings into Tibetan,",
    options: {
      A: "Kangyur",
      B: "Smritis",
      C: "Sutras",
      D: "None of these",
    },
    answer: "A",
  },
  {
    id: 35,
    question: "Which one is the oldest veda?",
    options: {
      A: "Rk veda",
      B: "Yajur Veda",
      C: "Sama veda",
      D: "Atharva Veda",
    },
    answer: "A",
  },
  {
    id: 36,
    question: "Which one is the sacred scriptures of the Jainism.",
    options: {
      A: "Upanishadas",
      B: "Agamas",
      C: "Puranas",
      D: "Mahayana",
    },
    answer: "B",
  },
  {
    id: 37,
    question:
      "During ancient Indian education system, education was provided in residential schools, which is known as.........................",
    options: {
      A: "Akhadas",
      B: "Sarayas",
      C: "Gurukulas",
      D: "Mathas",
    },
    answer: "C",
  },
  {
    id: 38,
    question: "Breathing exercises are also known as..................",
    options: {
      A: "Pranayama",
      B: "Asanas",
      C: "Chintan",
      D: "Manan",
    },
    answer: "A",
  },
  {
    id: 39,
    question:
      "Which place was famous for the pursuing meditation, contemplation, and philosophical inquiry under the guidance of a spiritual teacher (guru)?",
    options: {
      A: "Mathas",
      B: "Gurukulas",
      C: "Viharas",
      D: "Ashramas",
    },
    answer: "D",
  },
  {
    id: 40,
    question: "Mahayana Sutras are the .................scriptures.",
    options: {
      A: "Hindu",
      B: "Jain",
      C: "Sikkh",
      D: "Buddhist",
    },
    answer: "D",
  },
  {
    id: 41,
    question: "Which one is known as 5th veda in Hinduism?",
    options: {
      A: "Vedas",
      B: "Mahabhartha",
      C: "Ramayana",
      D: "Bhagvad Gita",
    },
    answer: "B",
  },
  {
    id: 42,
    question: "Charaka and Kautilya were the alumni of ........................",
    options: {
      A: "Takshashila",
      B: "Nalanda",
      C: "Vikramshila",
      D: "Vallabhi",
    },
    answer: "A",
  },
  {
    id: 43,
    question: "The golden period of Nalanda University was in between.................................",
    options: {
      A: "5th century CE and 12th century CE",
      B: "7th century CE and 11th century CE",
      C: "8th century CE and 15th century CE",
      D: "9th century CE and 10th century CE",
    },
    answer: "A",
  },
  {
    id: 44,
    question: "Vallabhi was a great center of learning which is located in the state of....................",
    options: {
      A: "Bihar",
      B: "Gujarat",
      C: "Madhya Pradesh",
      D: "Punjab",
    },
    answer: "B",
  },
  {
    id: 45,
    question: "Ether is among....................",
    options: {
      A: "Five elements",
      B: "Siksha",
      C: "Darshana",
      D: "None of these",
    },
    answer: "A",
  },
  {
    id: 46,
    question: "Total how many Nakshatras are mentioned in the ancient literatures?",
    options: {
      A: "8",
      B: "18",
      C: "23",
      D: "28",
    },
    answer: "D",
  },
  {
    id: 47,
    question: "Vedanga-Jyotisha was composed in..........",
    options: {
      A: "1000 BCE",
      B: "1100 BCE",
      C: "1200 BCE",
      D: "1300 BCE",
    },
    answer: "C",
  },
  {
    id: 48,
    question: "Yajnopavita is realted to.........................",
    options: {
      A: "Upnayana",
      B: "Grihstha",
      C: "Vanprastha",
      D: "None of these",
    },
    answer: "A",
  },
  {
    id: 49,
    question: "Arthashastra was written by.............",
    options: {
      A: "Aryabhatta",
      B: "Kautilya",
      C: "Panini",
      D: "Brahmgupta",
    },
    answer: "B",
  },
  {
    id: 50,
    question: "In which state, ancient Vikramshila University was located?",
    options: {
      A: "Uttar Pradesh",
      B: "Gujarat",
      C: "Madhya Pradesh",
      D: "Bihar",
    },
    answer: "D",
  },
  {
    id: 51,
    question: "What was the period of Aryabhata?",
    options: {
      A: "376–440 CE",
      B: "476–550 CE",
      C: "526–560 CE",
      D: "396–510 CE",
    },
    answer: "B",
  },
  {
    id: 52,
    question: "Siddhanta Shiromani is written by...........",
    options: {
      A: "Brahgupta",
      B: "Aryabhatta",
      C: "Bhaskara",
      D: "Kautilya",
    },
    answer: "C",
  },
  {
    id: 53,
    question: "Who gave Heliocentric model of the solar system?",
    options: {
      A: "Aryabhatta",
      B: "Brahgupta",
      C: "Bhaskara",
      D: "Kautilya",
    },
    answer: "A",
  },
  {
    id: 54,
    question: "The Indian calendar often integrates........",
    options: {
      A: "Only stars",
      B: "Only Lunar element",
      C: "Only Solar element",
      D: "Both lunar and solar elements",
    },
    answer: "D",
  },
  {
    id: 55,
    question: "How many ritus are there as The Indian calendar?",
    options: {
      A: "4",
      B: "6",
      C: "8",
      D: "10",
    },
    answer: "B",
  },
  {
    id: 56,
    question: "Which ancient Indian text describes mining and metallurgical techniques?",
    options: {
      A: "Rigveda",
      B: "Arthashastra",
      C: "Charaka Samhita",
      D: "Natya Shastra",
    },
    answer: "B",
  },
  {
    id: 57,
    question: "What was the primary fuel used for smelting metals in ancient India?",
    options: {
      A: "Coal",
      B: "Charcoal",
      C: "Cow dung",
      D: "Wood",
    },
    answer: "B",
  },
  {
    id: 58,
    question: "Which metal was extensively used in ancient India for making idols using the lost-wax technique?",
    options: {
      A: "Bronze",
      B: "Iron",
      C: "Zinc",
      D: "Copper",
    },
    answer: "A",
  },
  {
    id: 59,
    question: "What was the primary purpose of 'Kupya' in ancient Indian metallurgy?",
    options: {
      A: "A type of furnace",
      B: "A crucible for melting metals",
      C: "A bellow for air supply",
      D: "A hammer for forging",
    },
    answer: "A",
  },
  {
    id: 60,
    question: "Which of the following was NOT an alloy developed in ancient India?",
    options: {
      A: "Brass",
      B: "Bronze",
      C: "Stainless steel",
      D: "Pewter",
    },
    answer: "C",
  },
  {
    id: 61,
    question: "The famous Iron Pillar of Delhi is made up of which material?",
    options: {
      A: "Wrought Iron",
      B: "Cast Iron",
      C: "High-carbon steel",
      D: "Pure Iron",
    },
    answer: "A",
  },
  {
    id: 62,
    question: "Which ancient Indian metallurgist is known for advancements in iron smelting?",
    options: {
      A: "Nagarjuna",
      B: "Sushruta",
      C: "Varahamihira",
      D: "Patanjali",
    },
    answer: "A",
  },
  {
    id: 63,
    question: "Which of the following is a unique contribution of Indian Mathematics?",
    options: {
      A: "Calculus",
      B: "Complex Numbers",
      C: "Pythagorean Theorem",
      D: "Decimal System with Zero",
    },
    answer: "D",
  },
  {
    id: 64,
    question: "Which Indian mathematician introduced the concept of negative numbers?",
    options: {
      A: "Bhaskara II",
      B: "Brahmagupta",
      C: "Aryabhata",
      D: "Varahamihira",
    },
    answer: "B",
  },
  {
    id: 65,
    question: "The 'Pingala's Chandaḥ Śāstra' is associated with which mathematical concept?",
    options: {
      A: "Magic Squares",
      B: "Binary Numbers",
      C: "Trigonometry",
      D: "Algebra",
    },
    answer: "B",
  },
  {
    id: 66,
    question: "What is the unique feature of Indian trigonometry compared to Greek trigonometry?",
    options: {
      A: "Use of Sine (Jya) function",
      B: "Use of Angles",
      C: "Use of Tangents",
      D: "Use of Radians",
    },
    answer: "A",
  },
  {
    id: 67,
    question: "Which ancient Indian text contains the earliest known discussion of permutations and combinations?",
    options: {
      A: "Lilavati",
      B: "Yuktibhāṣā",
      C: "Chandah Sāstra",
      D: "Siddhanta Shiromani",
    },
    answer: "C",
  },
  {
    id: 68,
    question:
      "Which ancient Indian text is considered the most authoritative work on military strategy and statecraft?",
    options: {
      A: "Manusmriti",
      B: "Mahabharata",
      C: "Rigveda",
      D: "Arthashastra",
    },
    answer: "D",
  },
  {
    id: 69,
    question: "Who is regarded as the ancient Indian scholar who systematized military science and warfare strategies?",
    options: {
      A: "Chanakya",
      B: "Aryabhata",
      C: "Patanjali",
      D: "Panini",
    },
    answer: "A",
  },
  {
    id: 70,
    question: "What was the primary focus of military training in ancient India as described in the Arthashastra?",
    options: {
      A: "Physical strength only",
      B: "Archery and Swordsmanship",
      C: "Espionage and psychological warfare",
      D: "Combined training in weapons, strategy, and discipline",
    },
    answer: "D",
  },
  {
    id: 71,
    question:
      "Which ancient Indian kingdom was particularly known for its advanced military formations like the 'Chakravyuha'?",
    options: {
      A: "Maurya Empire",
      B: "Gupta Empire",
      C: "Magadha",
      D: "Mahajanapadas",
    },
    answer: "C",
  },
  {
    id: 72,
    question: "What was the primary purpose of Niyuddha Kala in ancient India?",
    options: {
      A: "Entertainment",
      B: "Military combat and self-defense",
      C: "Religious rituals",
      D: "Agricultural training",
    },
    answer: "B",
  },
  {
    id: 73,
    question: "Which ancient Indian text describes Niyuddha techniques and combat strategies?",
    options: {
      A: "Arthashastra",
      B: "Natya Shastra",
      C: "Manusmriti",
      D: "Agni Purana",
    },
    answer: "D",
  },
  {
    id: 74,
    question: "Which warrior-sage is traditionally associated with the origin of Niyuddha in Indian culture?",
    options: {
      A: "Dronacharya",
      B: "Parshuram",
      C: "Bhishma",
      D: "Karna",
    },
    answer: "B",
  },
  {
    id: 75,
    question: "Which of the following was a key principle of Niyuddha Kala?",
    options: {
      A: "Use of only long-range weapons",
      B: "Strict non-violence",
      C: "Discipline, ethics, and physical prowess",
      D: "Focus on magical powers",
    },
    answer: "C",
  },
  {
    id: 76,
    question: "Which Vedic concept represents the deification and sacredness of nature?",
    options: {
      A: "Yajna",
      B: "Pradushana",
      C: "Devata",
      D: "Prakriti",
    },
    answer: "C",
  },
  {
    id: 77,
    question: "In Vedic tradition, what does the term 'Prithvi' signify?",
    options: {
      A: "Goddess of Water",
      B: "Mother Earth",
      C: "God of Fire",
      D: "Divine Air",
    },
    answer: "B",
  },
  {
    id: 78,
    question: "Which Vedic practice reflects environmental conservation through ritual offerings?",
    options: {
      A: "Tapasya",
      B: "Yajna",
      C: "Dhyana",
      D: "Puja",
    },
    answer: "B",
  },
  {
    id: 79,
    question: "Which Vedic text emphasizes the interconnectedness of all natural elements?",
    options: {
      A: "Rigveda",
      B: "Atharvaveda",
      C: "Samaveda",
      D: "Yajurveda",
    },
    answer: "B",
  },
  {
    id: 80,
    question: 'The "Paradigm Shift" through IKS emphasizes:',
    options: {
      A: "Blending ancient wisdom with modern scientific methods",
      B: "Rejecting technological advancements",
      C: "Exclusively using Sanskrit terminology",
      D: "Reviving outdated practices without modification",
    },
    answer: "A",
  },
  {
    id: 81,
    question: "According to Bhartṛhari, what is the indivisible unit of linguistic communication?",
    options: {
      A: "Word",
      B: "Phoneme",
      C: "Sentence",
      D: "Meaning",
    },
    answer: "C",
  },
  {
    id: 82,
    question: 'The "Vigyan Jyoti" program encourages girls to pursue STEM fields by:',
    options: {
      A: "Teaching Vedic mathematics exclusively",
      B: "Combining traditional Indian sciences with modern STEM",
      C: "Focusing only on space technology",
      D: "Ignoring IKS completely",
    },
    answer: "B",
  },
  {
    id: 83,
    question: "Bhartṛhari's view that language and reality are inseparable aligns with which concept?",
    options: {
      A: "Śabda-pramana",
      B: "Yajna",
      C: "Pradushana",
      D: "Karma",
    },
    answer: "A",
  },
  {
    id: 84,
    question: "Which of the following is a key strategy to integrate IKS into modern education?",
    options: {
      A: "Incorporate traditional texts in STEM curricula",
      B: "Replace Western science entirely",
      C: "Limit IKS to history courses",
      D: "Ignore contemporary applications",
    },
    answer: "A",
  },
  {
    id: 85,
    question: "In Panini's Aṣṭādhyāyī, what is the primary mechanism for generating grammatical rules?",
    options: {
      A: "Random word lists",
      B: "Sutras with recursive operations",
      C: "Pictorial representations",
      D: "Oral traditions only",
    },
    answer: "B",
  },
  {
    id: 86,
    question: "Which of the following is a focus area of the IKS Division established under the Ministry of Education?",
    options: {
      A: "Preserving ancient manuscripts only",
      B: "Promoting only Ayurveda in schools",
      C: "Integrating IKS into mainstream education and research",
      D: "Translating all texts into English",
    },
    answer: "C",
  },
  {
    id: 87,
    question: "How does IKS contribute to environmental sustainability today?",
    options: {
      A: "Adapting ancient water management to modern ecology",
      B: "By reviving outdated farming tools",
      C: "Banning all industrial development",
      D: "Using only organic pesticides",
    },
    answer: "A",
  },
  {
    id: 88,
    question: "What makes Sanskrit uniquely suited for Natural Language Processing (NLP)?",
    options: {
      A: "Its ancient religious status",
      B: "Simple vocabulary",
      C: "Large number of speakers today",
      D: "Highly structured, rule-based grammar",
    },
    answer: "D",
  },
  {
    id: 89,
    question: "What is the primary purpose of Chandas (prosody) in ancient Indian literature?",
    options: {
      A: "Decorative wordplay",
      B: "Structural framework for poetic composition",
      C: "Religious rituals only",
      D: "Musical notation",
    },
    answer: "B",
  },
  {
    id: 90,
    question: "Which Vedic text is the earliest known source for the study of Chandas?",
    options: {
      A: "Rigveda",
      B: "Yajurveda",
      C: "Chandogya Upanishad",
      D: "Natya Shastra",
    },
    answer: "A",
  },
  {
    id: 91,
    question: "In prosody, a Guru (heavy syllable) is defined by:",
    options: {
      A: "Sacred meaning",
      B: "High pitch",
      C: "Length",
      D: "Position in the stanza",
    },
    answer: "C",
  },
  {
    id: 92,
    question: "What was the primary function of Gana (mnemonic syllables) in Sanskrit prosody?",
    options: {
      A: "To memorize Vedic hymns",
      B: "To classify poetic metres",
      C: "To teach grammar rules",
      D: "To compose musical notes",
    },
    answer: "B",
  },
  {
    id: 93,
    question: 'Which of these is NOT one of the "seven birds" (major Sanskrit metres)?',
    options: {
      A: "Anuṣṭubh",
      B: "Triṣṭubh",
      C: "Jagatī",
      D: "Kavya",
    },
    answer: "D",
  },
  {
    id: 94,
    question: "How did metres contribute to literary architecture in ancient India?",
    options: {
      A: "By standardizing emotional expression",
      B: "By providing rigid rhythmic frameworks for poetry",
      C: "By replacing grammatical rules",
      D: "Limiting creative freedom",
    },
    answer: "B",
  },
  {
    id: 95,
    question: "According to the Vedic model, how many levels (koshas) of consciousness are described?",
    options: {
      A: "3",
      B: "6",
      C: "5",
      D: "12",
    },
    answer: "C",
  },
  {
    id: 96,
    question: "The ancient Indian theory of speech (Vak) and cognition is primarily explored in which text?",
    options: {
      A: "Patanjali's Yoga Sutras",
      B: "Charaka Samhita",
      C: "Nyaya Sutras",
      D: "Mandukya Upanishad",
    },
    answer: "D",
  },
  {
    id: 97,
    question: "Which governmental initiative promotes IKS in current research and policy?",
    options: {
      A: "AYUSH Mission",
      B: "Digital India",
      C: "Make in India",
      D: "Swachh Bharat",
    },
    answer: "A",
  },
  {
    id: 98,
    question: "Which ancient Indian text explicitly mentions Anvīkṣikī as one of the four vital vidyās for statecraft?",
    options: {
      A: "Manusmriti",
      B: "Arthashastra",
      C: "Rigveda",
      D: "Natya Shastra",
    },
    answer: "B",
  },
  {
    id: 99,
    question: "The term Anvīkṣikī primarily refers to:",
    options: {
      A: "Military strategy",
      B: "Agricultural techniques",
      C: "Poetic composition",
      D: "Logical and philosophical reasoning",
    },
    answer: "D",
  },
  {
    id: 100,
    question: "Rajadharma in ancient Indian polity primarily emphasized:",
    options: {
      A: "Military conquests",
      B: "Duties and ethical responsibilities of a ruler",
      C: "Trade regulations",
      D: "Religious rituals",
    },
    answer: "B",
  },
  {
    id: 101,
    question: "Kautilya's Arthashastra is fundamentally a treatise on:",
    options: {
      A: "Poetic composition",
      B: "Astronomical calculations",
      C: "Statecraft, economics, and political strategy",
      D: "Ayurvedic medicine",
    },
    answer: "C",
  },
  {
    id: 102,
    question: "The Shulba Sutras in ancient India primarily dealt with:",
    options: {
      A: "Land measurement and taxation",
      B: "Military strategy",
      C: "Temple architecture",
      D: "Ayurvedic medicine",
    },
    answer: "A",
  },
  {
    id: 103,
    question:
      "Which ancient Indian text provides detailed guidelines for revenue collection and taxation under the Mauryan administration?",
    options: {
      A: "Manusmriti",
      B: "Arthashastra",
      C: "Rigveda",
      D: "Natya Shastra",
    },
    answer: "B",
  },
  {
    id: 104,
    question: "A key mechanism to integrate IKS into modern education is:",
    options: {
      A: "Incorporating traditional texts in interdisciplinary curricula",
      B: "Limiting IKS to history courses",
      C: "Promoting only theoretical study",
      D: "Ignoring Western sciences",
    },
    answer: "A",
  },
  {
    id: 105,
    question: "The Paradigm Shift expected from IKS integration emphasizes:",
    options: {
      A: "Isolating IKS from global systems",
      B: "Rejecting all contemporary knowledge",
      C: "Focusing on Sanskrit literature",
      D: "Blending ancient wisdom with modern scientific rigor",
    },
    answer: "D",
  },
  {
    id: 106,
    question: "What is the primary focus of the Indian Knowledge System (IKS)?",
    options: {
      A: "Modern scientific theories",
      B: "Ancient Indian intellectual traditions and their applications",
      C: "Western philosophies",
      D: "Contemporary technological advancements",
    },
    answer: "B",
  },
  {
    id: 107,
    question: "Which ancient Indian text is considered the oldest and forms the foundation of the Vedic literature?",
    options: {
      A: "Bhagavad Gita",
      B: "Rigveda",
      C: "Upanishads",
      D: "Mahabharata",
    },
    answer: "B",
  },
  {
    id: 108,
    question:
      "In ancient Indian mathematics, which numeral system was developed that significantly influenced global mathematics?",
    options: {
      A: "Roman numeral system",
      B: "Binary numeral system",
      C: "Decimal place value system",
      D: "Hexadecimal system",
    },
    answer: "C",
  },
  {
    id: 109,
    question: "Who is known as the 'Father of Indian Astronomy' for his seminal work 'Aryabhatiya'?",
    options: {
      A: "Varahamihira",
      B: "Brahmagupta",
      C: "Aryabhata",
      D: "Bhaskara I",
    },
    answer: "C",
  },
  {
    id: 110,
    question:
      "Which ancient Indian treatise is renowned for its detailed exposition on statecraft, economics, and military strategy?",
    options: {
      A: "Manusmriti",
      B: "Arthashastra",
      C: "Ramayana",
      D: "Mahabharata",
    },
    answer: "B",
  },
  {
    id: 111,
    question: "In the context of Indian linguistics, what is 'Panini' known for?",
    options: {
      A: "Developing the concept of zero",
      B: "Writing the epic Mahabharata",
      C: "Composing a comprehensive grammar of Sanskrit",
      D: "Establishing the principles of Ayurveda",
    },
    answer: "C",
  },
  {
    id: 112,
    question: "Which ancient Indian science focuses on health, wellness, and longevity through natural means?",
    options: {
      A: "Yoga",
      B: "Ayurveda",
      C: "Jyotisha",
      D: "Vaastu Shastra",
    },
    answer: "B",
  },
  {
    id: 113,
    question: "The 'Sulbasutras' are ancient Indian texts primarily concerned with which subject?",
    options: {
      A: "Astronomy",
      B: "Geometry and construction of altars",
      C: "Music and arts",
      D: "Medicine",
    },
    answer: "B",
  },
  {
    id: 114,
    question: "Which ancient Indian scholar is credited with the discovery of the concept of zero as a numeral?",
    options: {
      A: "Aryabhata",
      B: "Brahmagupta",
      C: "Bhaskara II",
      D: "Varahamihira",
    },
    answer: "B",
  },
  {
    id: 115,
    question: "In ancient Indian architecture, what is the significance of 'Vaastu Shastra'?",
    options: {
      A: "It is a treatise on dance and performance arts",
      B: "It provides guidelines on the design and layout of buildings and structures",
      C: "It is a manual on ancient warfare techniques",
      D: "It is a guide for agricultural practices",
    },
    answer: "B",
  },
  {
    id: 116,
    question: "Which of the following is a classical Indian dance form that originated in Tamil Nadu?",
    options: {
      A: "Kathak",
      B: "Bharatanatyam",
      C: "Odissi",
      D: "Kathakali",
    },
    answer: "B",
  },
  {
    id: 117,
    question: "The ancient Indian text 'Charaka Samhita' is associated with which field?",
    options: {
      A: "Astronomy",
      B: "Medicine",
      C: "Mathematics",
      D: "Music",
    },
    answer: "B",
  },
  {
    id: 118,
    question:
      "Which ancient Indian university was renowned for its vast library and attracted students from various parts of the world?",
    options: {
      A: "Takshashila",
      B: "Nalanda",
      C: "Vikramashila",
      D: "Vallabhi",
    },
    answer: "B",
  },
  {
    id: 119,
    question: "In the context of Indian philosophy, what does 'Advaita Vedanta' emphasize?",
    options: {
      A: "Duality between mind and body",
      B: "Non-dualism and the unity of the individual soul with the ultimate reality",
      C: "The importance of rituals and ceremonies",
      D: "The supremacy of devotional practices",
    },
    answer: "B",
  },
  {
    id: 120,
    question:
      "Who authored the ancient Indian text 'Natya Shastra', which serves as a comprehensive guide on performing arts?",
    options: {
      A: "Kalidasa",
      B: "Bharata Muni",
      C: "Tulsidas",
      D: "Valmiki",
    },
    answer: "B",
  },
  {
    id: 121,
    question: "The 'Panchatantra' is a collection of ancient Indian tales primarily intended to impart what?",
    options: {
      A: "Religious teachings",
      B: "Moral and ethical lessons",
      C: "Historical accounts",
      D: "Scientific knowledge",
    },
    answer: "B",
  },
  {
    id: 122,
    question: "Which ancient Indian text is considered a foundational work on yoga philosophy?",
    options: {
      A: "Bhagavad Gita",
      B: "Yoga Sutras of Patanjali",
      C: "Hatha Yoga Pradipika",
      D: "Gheranda Samhita",
    },
    answer: "B",
  },
  {
    id: 123,
    question: "In Indian classical music, what are the two primary systems?",
    options: {
      A: "Carnatic and Hindustani",
      B: "Folk and Classical",
      C: "Raga and Tala",
      D: "Sitar and Tabla",
    },
    answer: "A",
  },
  {
    id: 124,
    question: "Which ancient Indian text deals with the principles of love and human relationships?",
    options: {
      A: "Manusmriti",
      B: "Kamasutra",
      C: "Arthashastra",
      D: "Upanishads",
    },
    answer: "B",
  },
  {
    id: 125,
    question: "The 'Bhagavad Gita' is a part of which larger Indian epic?",
    options: {
      A: "Ramayana",
      B: "Mahabharata",
      C: "Vedas",
      D: "Puranas",
    },
    answer: "B",
  },
  {
    id: 126,
    question:
      "Which ancient Indian scholar made significant contributions to the field of metallurgy and is known for his work 'Rasaratnakara'?",
    options: {
      A: "Aryabhata",
      B: "Charaka",
      C: "Nagarjuna",
      D: "Varahamihira",
    },
    answer: "C",
  },
  {
    id: 127,
    question: "Which Indian system of knowledge focuses on ethical living, duties, and moral responsibilities?",
    options: {
      A: "Dharma Shastra",
      B: "Arthashastra",
      C: "Nyaya Sutra",
      D: "Vaastu Shastra",
    },
    answer: "A",
  },
  {
    id: 128,
    question: "The ancient Indian science of 'Jyotisha' is primarily concerned with which field?",
    options: {
      A: "Mathematics",
      B: "Astronomy and astrology",
      C: "Medicine",
      D: "Architecture",
    },
    answer: "B",
  },
  {
    id: 129,
    question:
      "Which Indian scripture contains detailed discussions on the four goals of life: Dharma, Artha, Kama, and Moksha?",
    options: {
      A: "Upanishads",
      B: "Bhagavad Gita",
      C: "Manusmriti",
      D: "Puranas",
    },
    answer: "C",
  },
  {
    id: 130,
    question: "The 'Brihat Samhita' by Varahamihira is an encyclopedic work covering topics related to which fields?",
    options: {
      A: "Medicine and surgery",
      B: "Astronomy, meteorology, and architecture",
      C: "Poetry and drama",
      D: "Religion and philosophy",
    },
    answer: "B",
  },
  {
    id: 131,
    question: "Which ancient Indian epic narrates the story of Lord Rama and his quest to rescue Sita?",
    options: {
      A: "Mahabharata",
      B: "Ramayana",
      C: "Bhagavad Gita",
      D: "Upanishads",
    },
    answer: "B",
  },
  {
    id: 132,
    question: "In Ayurveda, what does the term 'Tridosha' refer to?",
    options: {
      A: "Three types of food",
      B: "Three fundamental bodily humors (Vata, Pitta, Kapha)",
      C: "Three stages of life",
      D: "Three types of diseases",
    },
    answer: "B",
  },
  {
    id: 133,
    question: "Which ancient Indian university was known for specializing in Buddhist studies and higher education?",
    options: {
      A: "Takshashila",
      B: "Nalanda",
      C: "Vikramashila",
      D: "Ujjain",
    },
    answer: "C",
  },
  {
    id: 134,
    question: "The 'Ashtadhyayi' by Panini is a seminal work in which field?",
    options: {
      A: "Medicine",
      B: "Grammar and linguistics",
      C: "Astronomy",
      D: "Ethics",
    },
    answer: "B",
  },
  {
    id: 135,
    question: "Which Indian knowledge tradition emphasizes meditation and self-realization?",
    options: {
      A: "Vedanta",
      B: "Mimamsa",
      C: "Nyaya",
      D: "Samkhya",
    },
    answer: "A",
  },
  {
    id: 136,
    question: "Which branch of Indian philosophy is primarily concerned with logic and reasoning?",
    options: {
      A: "Nyaya",
      B: "Yoga",
      C: "Samkhya",
      D: "Vedanta",
    },
    answer: "A",
  },
  {
    id: 137,
    question: "The concept of 'Panch Mahabhuta' in Indian philosophy refers to which of the following?",
    options: {
      A: "Five types of meditation",
      B: "Five great elements (Earth, Water, Fire, Air, Space)",
      C: "Five branches of Ayurveda",
      D: "Five Vedic scriptures",
    },
    answer: "B",
  },
  {
    id: 138,
    question: "Who among the following is regarded as the pioneer of Indian logic (Nyaya)?",
    options: {
      A: "Gautama",
      B: "Kapila",
      C: "Patanjali",
      D: "Bhartrihari",
    },
    answer: "A",
  },
  {
    id: 139,
    question: "Which of the following is NOT a classical Indian musical instrument?",
    options: {
      A: "Sitar",
      B: "Veena",
      C: "Tabla",
      D: "Guitar",
    },
    answer: "D",
  },
  {
    id: 140,
    question: "The 'Sushruta Samhita' is an ancient Indian text that deals with which field?",
    options: {
      A: "Astronomy",
      B: "Surgery and medicine",
      C: "Architecture",
      D: "Philosophy",
    },
    answer: "B",
  },
  {
    id: 141,
    question: "Which Indian philosophy focuses on cause and effect and is considered dualistic in nature?",
    options: {
      A: "Samkhya",
      B: "Vedanta",
      C: "Mimamsa",
      D: "Charvaka",
    },
    answer: "A",
  },
  {
    id: 142,
    question: "Which of the following was an ancient Indian center of learning located in present-day Pakistan?",
    options: {
      A: "Takshashila",
      B: "Nalanda",
      C: "Vikramashila",
      D: "Ujjain",
    },
    answer: "A",
  },
  {
    id: 143,
    question: "The concept of 'Rasa' in Indian aesthetics refers to which of the following?",
    options: {
      A: "Ayurvedic medicine preparation",
      B: "The essence or sentiment in performing arts",
      C: "A type of Indian dance form",
      D: "A Vedic ritual",
    },
    answer: "B",
  },
  {
    id: 144,
    question: "Who composed the classical Sanskrit play 'Shakuntala'?",
    options: {
      A: "Kalidasa",
      B: "Bharata Muni",
      C: "Valmiki",
      D: "Tulsidas",
    },
    answer: "A",
  },
  {
    id: 145,
    question: "Which ancient Indian scripture describes the duties and responsibilities of a ruler?",
    options: {
      A: "Manusmriti",
      B: "Arthashastra",
      C: "Vedas",
      D: "Upanishads",
    },
    answer: "B",
  },
  {
    id: 146,
    question: "Which text is considered the foundational scripture of the Samkhya philosophy?",
    options: {
      A: "Yoga Sutras",
      B: "Samkhya Karika",
      C: "Vedanta Sutra",
      D: "Bhagavad Gita",
    },
    answer: "B",
  },
  {
    id: 147,
    question: 'Which ancient Indian text is known as the "Fifth Veda" due to its comprehensive nature?',
    options: {
      A: "Bhagavad Gita",
      B: "Natya Shastra",
      C: "Upanishads",
      D: "Mahabharata",
    },
    answer: "B",
  },
  {
    id: 148,
    question: "The concept of 'Karma' in Indian philosophy primarily refers to:",
    options: {
      A: "Fate predetermined by the gods",
      B: "The law of cause and effect governing actions",
      C: "Ritualistic sacrifices",
      D: "The pursuit of pleasure",
    },
    answer: "B",
  },
  {
    id: 149,
    question: "Who is considered the father of Ayurveda?",
    options: {
      A: "Charaka",
      B: "Sushruta",
      C: "Nagarjuna",
      D: "Brahmagupta",
    },
    answer: "A",
  },
  {
    id: 150,
    question: "Which Indian scripture is primarily a dialogue between Nachiketa and Yama (the god of death)?",
    options: {
      A: "Katha Upanishad",
      B: "Mundaka Upanishad",
      C: "Bhagavad Gita",
      D: "Brahma Sutra",
    },
    answer: "A",
  },
  {
    id: 151,
    question: "Which of the following is NOT a traditional Indian martial art?",
    options: {
      A: "Kalaripayattu",
      B: "Silambam",
      C: "Gatka",
      D: "Judo",
    },
    answer: "D",
  },
  {
    id: 152,
    question: "The 'Puranas' primarily deal with:",
    options: {
      A: "History, mythology, and cosmology",
      B: "Military strategies",
      C: "Medical sciences",
      D: "Grammar and linguistics",
    },
    answer: "A",
  },
  {
    id: 153,
    question: "Which ancient Indian text describes the laws of motion and gravity before Newton?",
    options: {
      A: "Surya Siddhanta",
      B: "Charaka Samhita",
      C: "Arthashastra",
      D: "Nyaya Sutra",
    },
    answer: "A",
  },
  {
    id: 154,
    question: "What is the literal meaning of 'Vedanta'?",
    options: {
      A: "End of the Vedas",
      B: "Science of life",
      C: "Cosmic order",
      D: "Sacred law",
    },
    answer: "A",
  },
  {
    id: 155,
    question: "Which Indian philosophy emphasizes devotion (bhakti) as a path to liberation?",
    options: {
      A: "Vedanta",
      B: "Bhakti Yoga",
      C: "Nyaya",
      D: "Charvaka",
    },
    answer: "B",
  },
]
